# Welcome to Jekyll!

# Site settings
title: UEPL Project
email: t.becht@hs-mannheim.de
description: >- # this means to ignore newlines until "baseurl:"
 Hosting location for the project Überall Programmieren Lernen

baseurl: "UEPL" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
